site_name: 'Remu-botti Wiki'

theme:
  name: 'material'
  custom_dir: overrides
  palette:
    scheme: 'slate'
  icon:
    logo: PPemojis/remu-botti-logo
  favicon: images/remu-botti-logo.png

markdown_extensions:
  # Footnotes
  - footnotes
  # Code blocks
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  # Emojis
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  # Checkboxes
  - pymdownx.tasklist:
      custom_checkbox: true
  # Admonitions
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

plugins:
  # Navigation page ordering
  - awesome-pages
  - search

copyright: |
  Jesse Heikkinen in 2024.