name: ci 
on:
  push:
    branches:
      - master 
<<<<<<< HEAD
<<<<<<< HEAD
=======
      - main
>>>>>>> b68b48d (delete procfile, add feature to mkdocs.yml, added ci.yml to deploy to github pages)
=======
>>>>>>> b3f3fe2 (removed main from ci.yml)
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install \ 
              mkdocs-material \ 
              mkdocs-awesome-pages-plugin \
<<<<<<< HEAD
<<<<<<< HEAD
      - run: mkdocs gh-deploy --force
=======
      - run: mkdocs gh-deploy --force
>>>>>>> b68b48d (delete procfile, add feature to mkdocs.yml, added ci.yml to deploy to github pages)
=======
      - run: mkdocs gh-deploy --force
>>>>>>> 919203c (Update ci.yml)
